describe_topic:
  description: >
    "we are mentoring to create the best Agentic AI Engineers. Today we teach {}"

  expected_output: >
    "The students will be able to understand and master the concept of Agentic AI.{topic}"

  agent: sir_zia    