describe_topic:
  description: >
    "we are mentoring to create the best Agentic AI Engineers"

  expected_output: >
    "The students will be able to understand and master the concept of Agentic AI.{}"

  agent: sir_zia    