[project]
name = "lgapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Umair Pirzada", email = "129576257+UmairPirzada@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain-google-genai>=2.0.9",
    "langgraph>=0.2.70",
    "python-dotenv>=1.0.1",
]

[project.scripts]
lgapi = "lgapi:main"
simple_flow = "lgapi.simple_workflow:run_"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
