[project]
name = "multiple-agents"
version = "0.1.0"
description = "Multiple agents working together using CrewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai>=0.11.0",
    "python-dotenv>=0.19.0",
    "pyyaml>=6.0.1",
    "langchain-google-genai>=0.0.5",
    "google-generativeai>=0.3.2",
]

[project.scripts]
mul-agents = "multiple_agents.main1:kickoff"
mul-agents-1 = "multiple_agents.main2:kickoff"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "flow"

[tool.hatch.build.targets.wheel]
packages = ["src/multiple_agents"]
