[project]
name = "uv-tetris"
version = "0.1.0"
description = "A Tetris game implementation using UV and Streamlit"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "streamlit>=1.32.0",
    "numpy>=1.24.0",
    "pygame>=2.5.0"
]
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.ruff]
line-length = 88
target-version = "py38" 