[project]
name = "project2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Umair Pirzada", email = "129576257+UmairPirzada@users.noreply.github.com" }
]
requires-python = ">=3.13.1"
dependencies = []

[project.scripts]
project2 = "project2:main"
piaic = "project2:func"
nastp = project2.hello

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
