[project]
name = "uv-demo"
version = "0.1.0"
description = "A demo project showing uv package manager features"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=23.0",
    "mypy>=1.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"] 